name: Build BloodMoon

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout BloodMoon kernel source
      uses: actions/checkout@v4
      with:
        repository: kaderbava/android_kernel_realme_sdm710
        path: kernel_realme_sdm710
        ref: 13

    - name: Checkout vendor source
      uses: actions/checkout@v4
      with:
        repository: Not4GoodBoyThou/vendor_realme_RMX1971
        path: vendor_realme_RMX1971
        ref: 13    

    - name: Checkout zipper
      uses: actions/checkout@v4
      with:
        repository: Not4GoodBoyThou/AnyKernel3
        path: AnyKernel3

    - name: Android kernel build
      uses: Not4GoodBoyThou/android-kernel-actions@master
      id: build
      env:
        NAME: BloodMoon5Pro
        KERNEL_PATH: kernel_realme_sdm710
        ZIPPER_PATH: AnyKernel3
        VENDOR_PATH: vendor_realme_RMX1971
        PYTHON_VERSION: 3
      with:
        arch: arm64
        compiler: aosp-clang/android12-release/clang-r416183b/binutils
        defconfig: sdm670_defconfig
        image: Image.gz-dtb

    - name: Setup ccache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: build-kernel-arm64_BloodMoon
        max-size: 4G
        
    - name: Release build
      uses: appleboy/telegram-action@master
      with:
          to: ${{ secrets.CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: BloodMoon5Pro Kernel is built!, took ${{ steps.build.outputs.elapsed_time }} seconds.
          document: ${{ steps.build.outputs.outfile }}
