name: Build StockKernel

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Kharame kernel source
      uses: actions/checkout@v4
      with:
        repository: realme-kernel-opensource/realme_Q_3pro_5pro_X_XT-AndroidR-kernel-source
        path: kernel_realme_sdm710
        ref: master

    - name: Checkout vendor source
      uses: actions/checkout@v4
      with:
        repository: Not4GoodBoyThou/vendor_realme_RMX1971
        path: vendor_realme_RMX1971
        ref: 13    

    - name: Checkout zipper
      uses: actions/checkout@v4
      with:
        repository: Not4GoodBoyThou/AnyKernel3
        path: AnyKernel3

    - name: Android kernel build
      uses: Not4GoodBoyThou/android-kernel-actions@master
      id: build
      env:
        NAME: StockKernel
        KERNEL_PATH: kernel_realme_sdm710
        ZIPPER_PATH: AnyKernel3
        VENDOR_PATH: vendor_realme_RMX1971
        PYTHON_VERSION: 3
      with:
        arch: arm64
        compiler: aosp-clang/android12-release/clang-r416183b/binutils
        defconfig: sdm670-perf_defconfig
        image: Image.gz-dtb
        
    - name: Release build
      uses: appleboy/telegram-action@master
      with:
          to: ${{ secrets.CHANNEL_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: Stock Kernel is built!, took ${{ steps.build.outputs.elapsed_time }} seconds.
          document: ${{ steps.build.outputs.outfile }}
